language: php

php:
    - 7.3

before_script:
    - composer install --dev -v --prefer-source

script:
    - bin/phpspec run -fpretty --verbose --no-interaction
    - bin/phpstan analyse src --level=7
    - bin/phpcs
    - bin/console security:check