language: php

php:
    - 7.3

services:
    - mysql

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini

install:
    - composer install -v
    - yarn install
    - yarn encore dev

before_script:
    - make start

script:
    - bin/phpstan analyse src/ --level=7
    - bin/phpcs
    - bin/console security:check
    - bin/phpspec run -fpretty --no-interaction -v
    - bin/behat -v
    - bin/console doc:schema:validate