course_controllers:
    resource: ../../src/Course/Controller
    type: annotation

landing_controllers:
    resource: ../../src/Landing/Controller
    type: annotation

logbook_controllers:
    resource: ../../src/Logbook/Controller
    type: annotation

security_controllers:
    resource: ../../src/Security/Controller
    type: annotation
